"""first migration

Revision ID: 4bd4c141d80f
Revises: 
Create Date: 2021-10-24 14:40:28.852597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd4c141d80f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.String(), nullable=False),
    sa.Column('v0', sa.String(), nullable=True),
    sa.Column('v1', sa.String(), nullable=True),
    sa.Column('v2', sa.String(), nullable=True),
    sa.Column('v3', sa.String(), nullable=True),
    sa.Column('v4', sa.String(), nullable=True),
    sa.Column('v5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('v0', 'v1', name='_v0_v1_uc')
    )
    op.create_index(op.f('ix_casbin_rule_id'), 'casbin_rule', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_casbin_rule_id'), table_name='casbin_rule')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
